---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    description: ""
  generation: 1
  labels:
    app: terminal.default
    name: dopware-44-73-terminal
  name: terminal-xcbgj
  namespace: shuifeng
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: terminal.default
      name: dopware-44-73-terminal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        description: ""
      labels:
        app: terminal.default
        appId: "572"
        name: dopware-44-73-terminal
      name: terminal-xcbgj
      namespace: shuifeng
    spec:
      containers:
        - name: terminal-xcbgj
          image: registry.cn-hangzhou.aliyuncs.com/jcops/terminal:v1
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: "1717986918"
      securityContext:
        privileged: false
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: terminal.default
    name: dopware-44-73-terminal
  name: terminal
  namespace: shuifeng
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: tcp-28088-8089-2jhl9
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: terminal.default
    name: dopware-44-73-terminal
  sessionAffinity: None
  type: NodePort
